### ISSUE TITLE
Update editorial community summary for PeerJ

### ISSUE THREAD

**Issue by BlueReZZ** [libero/prc#142]
## Definition of Done:

- [x] new text content and logo is available on staging
- [x] Nathaniel Gore at PeerJ has approved it

Text should now read as per the updated page in https://docs.google.com/document/d/1lFcM_XhUZKYRbq2hqNdfijnRaWfsXNZ0DnaJHxdY-3I/edit#heading=h.i20faaopvi9m 

## Tasks

- [x] Update the text as described above
- [x] Add their logo (official logos here: https://peerj.com/about/press/)

**Comment by giorgiosironi** [comment]
Available on http://prc-staging.libero.pub/editorial-communities/53ed5364-a016-11ea-bb37-0242ac130002

**Comment by giorgiosironi** [comment]
Style refinement still needed.

Question: should we host the logos ourselves (including the eLife one) or can we continue hotlinking to other websites?

**Comment by BlueReZZ** [comment]
I just emailed Nathaniel for some feedback on the page.

I don't have a strong opinion on hot linking of images, my experience is that hosting them ourselves is better in the long run as we can utilise our own CDN caching strategies for it but we're a long way of micro-optimising web performance at the moment.

**Comment by thewilkybarkid** [comment]
Only issue will be when introducing HTTPS, as the PeerJ one is only available over HTTP. So something we can resolve then.

**Comment by BlueReZZ** [comment]
Received positive response from Nathaniel:
> Hi Paul,
> 
> That looks great, thanks. Let me know if you need anything re. the content upload. We look forward to seeing it!
> 
> Cheers,
> 
> Nathaniel
