### ISSUE TITLE
Hide 0 counts in search results

### ISSUE THREAD

**Issue by hdrury1** [libero/prc#167]
In the absence of filtering tools, a reader is scanning a list of search results to determine which article is worthy of their time investment. We should make the distinction between articles which have valuable discourse and those which do not visually clearer by hiding any 'zero' result.

### Tasks

- [x] Hide `Comments: 0` from returned results
- [x] Hide `Comments: n/a` from returned results
- [x] Hide `Reviews: 0` from returned results
