### ISSUE TITLE
Deploy new revisions of frontend coming from master

### ISSUE THREAD

**Issue by giorgiosironi** [libero/prc#3]
## Tasks

- [x] Add Helm chart
- [x] Test chart locally
- [x] Deploy manually to `prc--prod` on Franklin cluster
- [x] Add to build
